@startuml 
/' Alt+d pour ouvrir et reload la visualisation '/


/' Parametrage pour la structuration d'une BdD '/
!define primary_key(x) <b><color:#FF0000><&key></color> x</b>
!define foreign_key(x) <color:#17B419><&key></color> x
!define column(x) <color:#7F9EEB><&media-record></color> x
!define table(x) entity x << (T, white) >>

!define UNIQUE <color:#AF990B><UNIQUE></color>
!define ENUM <color:#AF990B>ENUM</color>
!define VARCHAR <color:#F78B19>VARCHAR</color>
!define INT <color:#F78B19>INT</color>
!define DATE <color:#F78B19>DATE</color>
!define BLOB <color:#F78B19>BLOB</color>
!define BOOL <color:#F78B19>BOOL</color>
!define JSON <color:#F78B19>JSON</color>
!define TIMESTAMP <color:#F78B19>TIMESTAMP</color>
!define TEXT <color:#F78B19>TEXT</color>




/'--------------- Tables USERS/SENSORS ---------------'/

table(Utilisateur) {
  primary_key(id) : UNIQUE INT [31]
  column(typeUser) : ENUM {User, Modo, Admin}
  
  column(photo) : BLOB
  column(firstName) : VARCHAR [31]
  column(lastName) : VARCHAR [31]
  column(birthday) : DATE

  column(phoneNumber) : UNIQUE VARCHAR [20]
  column(mail) : UNIQUE VARCHAR [63]
  column(password) : hash VARCHAR [63]

  column(country) : VARCHAR [31]
  column(city) : VARCHAR [31]
  column(codePostal) : INT [7]
  column(address) : VARCHAR [63]
  
  foreign_key(id_sensor) : UNIQUE VARCHAR [31]
}


table(sensorBox) {
  primary_key(id_sensorBox) : UNIQUE VARCHAR [31]
}


table(sensor) {
  primary_key(id_sensor) : UNIQUE VARCHAR [31]
  foreign_key(id_sensorBox) : VARCHAR [31]
  column(typeSensor) : ENUM {temperatureSensor,heartSensor,humiditySensor, soundSensor}
  column(isUsed) : BOOL
  column(isNotBroken) : BOOL
}


table(dataSensor) {
  primary_key(id_data): UNIQUE VARCHAR [31]
  foreign_key(id_sensor): VARCHAR [31]
  column(dataFile) : JSON
  column(dateStart) : TIMESTAMP
  column(dateEnd) : TIMESTAMP
}



/'--------------- Jointure ---------------'/
/'WHERE user.id_sensor = sensor.id_sensor ANDD 1-1 for 1-1'/
Utilisateur ||--|| sensorBox :0-1\n\n0-1
sensorBox ||--|{ sensor : 0-1\n\n0-4
sensor ||-|{ dataSensor : 1-1     0-*



/'--------------- Tables FAQ ---------------'/

table(FAQ) {
  primary_key(id_question): UNIQUE INT [31]
  column(question) : TEXT
  column(response) : TEXT  
}



/'--------------- Explication littéral ---------------'/

/' 
Un User a :* nom
           * prénom
           * date de naissance
           * phone
           * mail
           * lieu de vie 
Pour se connecter, un User doit utiliser son mail et un mot de passe.
Un User doit donc avoir un mail unique ainsi qu'un identifiant unique.
Un User possède un boitier APPNEA.

Un boitier APPNEA contient des capteurs : * capteur cardiaque
                                          * capteur sonore
                                          * capteur de température
                                          * capteur d'humidité
Chaque capteur récolte des données à un moment t
Un ADMIN peut gérer les capteurs (activation/désactivation).

Un Modo et un Admin sont similaire aux User mais ne possèdent pas de boitier APPNEA.
Un Modo peut gérer la FAQ. La FAQ contient des questions et des réponses.
Un ADMIN peut gérer les utilisateurs (ajouter, supprimer, modifier, bannir) (USER et MODO).
Les utilisateurs sont les USER, MODO, ADMIN
'/

/'
Comment se passe le transfère des data de la carte au serveur ?
  - 1 ligne dans la base = 1 seconde et une valeur (surcharge de la co)
  - 1 ligne dans la base = 1 nuit (actualisation seulement quand la carte est off)
  - 1 ligne dans la base = 1 heure avec toutes les données à la seconde
  - 1 ligne dans la base = 1 ...

on peut donc avoir plusieurs type de colonne
  * date - json/csv
  * date - value
  * json/csv avec date+date compris

'/

@enduml